### PR TITLE
DICOM Fidelity Check failure

### PR DESCRIPTION
**Pull request by tcpan**
Previous implementation stored gain * measurements directly, which for some datasets (e.g. Charis8 and Charis9) and some channels (e.g. ABP, ICP) can overflow the value type (e.g. int16).

This pull request changes the encoding to scale the value range to that of the value type. limited testing passed.   It has yet to be tested against Charis8 and Charis9).

### CODE REVIEW

**Comment by briangow** [comment]
@tcpan this is still failing for me:

```
________________________________________________________________
Format: waveform_benchmark.formats.dicom.DICOMLowBits
Record: /home/briangow/chorus/data/waveform_benchmark/waveforms/charisdb/1.0.0/charis8
         343399 seconds x 3 channelsorus_waveform$ 
         51509871 timepoints, 51509871 samples (100.0%)
________________________________________________________________
Channel summary information:repos/chorus_waveform$ 
 signal       fs(Hz)     Bit resolution       Channel length(s)   
 ABP          50.00      0.0113(mmHg)         343399              
 ECG          50.00      0.000164(mV)         343399              
 ICP          50.00      0.012(mmHg)          343399              
________________________________________________________________
Output size:    100609 KiB (16.00 bits/sample)
Time to output: 1 secric Samples		  NaN Samples
Wall Time: 1 sench:~/chorus/repos/chorus_waveform$ 
Maximum Memory Used: 865 MiB
________________________________________________________________
Fidelity check:ual numeric data from input:
briangow@wavebench:~/chorus/repos/chorus_waveform$ 
Chunk663546      Numeric Samples9038036   0.9263  NaN Samples41  ]
Subset o# Errors  /  Total data   % Eq  matted fNaN Values Match
Signal: ABPvebench:~/chorus/repos/chorus_waveform$ 
  0  669   1355289/  171699570.092.1072   0.9201     Y (0)      6]
Subset of unuequal numeric data from input:veform$ 
[  6.1232696   -3.0277421   -8.5635395    9.8514595  -26.18771
  18.663546     1.1523496   -0.09038036   0.92639875 -21.442741  ]
Subset of unuequal numeric data from formatted file:
[  6.11702561  -3.03392425  -8.56968404   9.84519037 -26.19373562
  18.6697689    1.14613926  -0.09658232   0.92018989 -21.44879866]
(Gain: 88.5148)
Signal: ECG
  0  	   1829290/  17169957	89.346		     Y (0)      
Subset of unuequal numeric data from input:
[ 0.0753101   0.05557819 -0.0480143  -0.00361752 -0.01841644 -0.00855049
 -0.00855049  0.01611439 -0.00197319 -0.06281322]
Subset of unuequal numeric data from formatted file:
[ 0.07540123  0.05566946 -0.04810503 -0.00370855 -0.01850738 -0.00864149
 -0.00864149  0.01602322 -0.00206423 -0.06290386]
(Gain: 6081.5219)
Signal: ICP
  0  	   1042065/  17169957	93.931		     Y (0)      
Subset of unuequal numeric data from input:
[9.122133  5.8728247 5.3914456 8.761099  7.798341  7.316962  4.789722
 3.9473083 2.1421368 2.3828263]
Subset of unuequal numeric data from formatted file:
[9.12872638 5.87943986 5.39806408 8.76769454 7.80494298 7.3235672
 4.79634436 3.95393674 2.14877756 2.38946545]
(Gain: 83.0946)
```

You can pull the charis8 file to your local machine by running: 
`wget -r -N -c -np https://physionet.org/files/charisdb/1.0.0/charis8.hea`
`wget -r -N -c -np https://physionet.org/files/charisdb/1.0.0/charis8.dat`

**Comment by tcpan** [comment]
I think we are at the limit of the standard in terms of numeric precision.  The internal array datatype is 16 bit integer for ABP and ICP (hemodynamics), as well as for ECG (ambulatory ECG).   The encoded values are rounded, and based on my test this is the source of the numeric differences.  I've tried to increase the dynamic range of the encoded values in order to minimize impact on numeric precision from the rounding, but it's still there.   The other factor that seems to compound the problem is that the input values for Charis8 have a dynamic range of 740.3737, which is then mapped to encoded values with a dynamic range of 90% of 65534.  Basically, we are seeing the quantization errors.

I am open to any solutions to this problem.  thanks!

**Comment by briangow** [comment]
@tcpan , sorry I haven't had a chance to look at this. I know we had a similar error with CCDEF and @wa6gz fixed it by using the baseline calculation from the WFDB code. Do you know of a reason why that won't work for DICOM?

**Comment by tcpan** [comment]
Fixes checked in - these have been tested on 5 datasets and pass.  Please note that DICOMHighBitsMerged, DICOMLowBitsMerged have been commented out - they are not as useful and it's hard to deal with multiple gains in the same channel in that chunking scheme. 

Also added DICOM16Bits and DICOM16BitsChunked, and a "--test_only" flag for the benchmark.

**Comment by tompollard** [comment]
@tcpan I see the benchmark script is failing, sorry. I can take a look to try to fix it if helpful? It might be easiest to tweak the following chunk to not error-out if there are no results to compile.

https://github.com/chorus-ai/chorus_waveform/blob/3e24bc5e8fa551cc657ba94e805ca60f1b39f577/.github/workflows/benchmark.yml#L112-L116

**Comment by tcpan** [comment]
@tompollard, I think this failure has been showing up for a while and I am not sure what is wrong with this. 
  I believe every run would generate results so there should not be missing or empty files. 

So help in debugging this would be great.

**Comment by tcpan** [comment]
BTW, the DICOM16Bits and DICOMLowBits are equivalent in our test, because we do not use 8bit DICOM IODs.  similarly for DICOM16BitsChunked and DICOMLowBitsChunked.   For benchmarking, we do not need to switch to the new class names.

**Comment by briangow** [comment]
> BTW, the DICOM16Bits and DICOMLowBits are equivalent in our test, because we do not use 8bit DICOM IODs. similarly for DICOM16BitsChunked and DICOMLowBitsChunked. For benchmarking, we do not need to switch to the new class names.

@tcpan thanks for this clarification, I was a little confused about why you had the redundant classes. I'm assuming you prefer to keep it this way in case we allow have 8bit DICOM IODs in the future? 

I'll run this across the files used for waveform benchmarking.

**Comment by tcpan** [comment]
the "just in case" is indeed my thinking.  Thanks, Brian.

**Comment by briangow** [comment]
@tcpan , I'm getting a `KeyError: 'III'` for this waveform `mimic3wdb/1.0/36/3654093/3654093`. The `III` signal is only 10s long (with NaNs). You can download this WFDB file from PN with: `wget -r -N -c -np https://physionet.org/files/mimic3wdb/1.0/36/3654093/`

**Comment by tcpan** [comment]
The III signal appears to only contain NaN.  Previously I excluded such data from being written out.   Now I am allowing write out of such signals.   An alternative is to return NaN arrays on read if no matching channel is found, but that seems to be a more confusing strategy.

**Comment by briangow** [comment]
@tcpan , thanks, this is now running without error across the waveform file suite.

**Pull request merged**
