### PR TITLE
Update function signature and requirements.txt for atriumdb 2.4.0

### PR DESCRIPTION
**Pull request by WilliamDixon**
Minor name change and requirements.txt update so format will work correctly with official released version of atriumdb.

### CODE REVIEW

**Comment by tompollard** [comment]
@WilliamDixon please could you move the requirements change to a separate PR? I'd like to merge this first, then make a decision about whether or not to remove the benchmark test. As far as I can see, it's been failing for a while as a result of #103.

**Comment by WilliamDixon** [comment]
> @WilliamDixon please could you move the requirements change to a separate PR? I'd like to merge this first, then make a decision about whether or not to remove the benchmark test. As far as I can see, it's been failing for a while as a result of #103.

Sure no problem, I should note that the current version in the main repo's requirements.txt is currently 2.2.4, a version that doesn't exist (my fault), so I expect if I remove the change to the requirements.txt any attempts to pip install the requirements will fail.

**Comment by tompollard** [comment]
> Sure no problem, I should note that the current version in the main repo's requirements.txt is currently 2.2.4, a version that doesn't exist (my fault), so I expect if I remove the change to the requirements.txt any attempts to pip install the requirements will fail.

Thanks! Where we can find the working version of the package? I'd like to work out whether we should just remove the existing tests that rely on the requirements, or whether it's an easy fix once the requirements are correctly specified.

**Comment by tompollard** [comment]
@WilliamDixon please could you rebase on the main branch?

**Comment by WilliamDixon** [comment]
@tompollard Is the Error in the test: Benchmark new formats / benchmark-new-formats (3.10) (pull_request) preventing you from merging this PR, I'm not sure what the error is exactly pointing to, although since my change is just updating a variable name to match the new AtriumDB API I would guess that same error is present in the main branch.

When I unit test the main branch with AtriumDB now I run into NotImplemented errors from #94 because I haven't implemented the new methods, but prior to that branch everything seemed to run smoothly.

**Comment by tompollard** [comment]
sorry @WilliamDixon, I think tests should now pass if you rebase on main.

**Comment by briangow** [comment]
@WilliamDixon , could you have a look at the failure in the tests. I am able to reproduce this against this waveform: `./data/waveforms/mimic_iv/waves/p100/p10079700/85594648/85594648`. However, the error doesn't occur when running this waveform: `./data/waveforms/mimic_iv/waves/p169/p16955095/82284982/82284982`. The issue appears to be with NaNs in the `output_signal`. It is likely this issue was introduced in an already merged PR but it would be good to get your feedback before merging this PR.

**Comment by WilliamDixon** [comment]
@briangow Hey brian, looking into the error, it looks like if the nan positions of the read waveforms differ from the benchmark's source of truth, this error is inevitable.

If you want to check your yourself take a look at line 357 of benchmark.py and then follow down to where:

`filedata_nonan = filedata[~np.isnan(data)]`

The format's filedata is getting the ~nan_mask of the source of truth's data, and so if the nan positions were different, the `filedata_nonan`  variable will still have nans.

But a little further down in:

`snr = compute_snr(data_nonan, filedata_nonan)`

One of the first lines asserts that `np.all(np.isfinite(output_signal))` which fails if output_signal/filedata_nonan has nan values.

So I'm trying to fix the code so that the fidelity is 100% again, but after that I'll open an issue that formats without 100% fidelity crash instead of of reporting the fact and continuing with the benchmark.

**Comment by WilliamDixon** [comment]
Looked into this a lot further this afternoon, looks like an issue in how the positions of the nan values should be replaced when the frequencies correspond to periods with large decimals, like 249.89 Hz.

Unclear how AtriumDB was passing the test previously. Possibly the benchmark code would note the nan's were in the wrong place in those instances but it just wasn't a big deal.

I've almost fixed the issue, but one signal seems to have an off-by-one issue I can't seem to square atm. Will take a closer look on Monday.

**Comment by WilliamDixon** [comment]
@tompollard @briangow So the issue was occurring when we have non-simple frequencies like 124.94 Hz, the bisect algorithm I was using (`np.searchsorted`) to filter unneeded data would occasionally be off-by-one compared to what the benchmark was expecting.

### Data Truncation Off-By-One

If we had samples saved at times:

`2077022.76994706 and 207702.284998227`

and the start time requested was `207702.2689983593` then `searchsorted` was giving us `207702.284998227`, when the benchmark expects `2077022.76994706`.

Then when atriumdb's time, value pair data was converted to the Chorus nan-standard, the first data point would be missing and therefore would be replaced with a nan value.

So the simple fix was to detect if the start time is strictly less that the chosen truncated time, and if it is, reduce the chosen index by 1.

### compute_snr Bug

And as I mentioned earlier in this thread, I think there's a bug in the benchmark code in and around `compute_snr` where if the positions of nan values are not perfectly equal in the format's read_waveforms to the expected result then the Error we've been seeing is inevitable. And this coupled with the off-by-one truncation was causing the error message we kept hitting trying to merge this branch.

### Open Once Read Many

I've also added to our branch an implementation of open-once-read-many. Since AtriumDB is more of a database than a format, it doesn't have an easy analog to leaving a file open and disk reading it over and over, so instead during the file open step, we read in the compressed bytes of the signal, and then in `read_opened_waveforms`, we decompress the desired blocks directly from RAM. This gives us a meaningful speed boost for very small reads, but no difference when reading the entire file.

**Comment by briangow** [comment]
@WilliamDixon , would you be able to rebase on `main` one more time to see if we've fixed all of the issues with the tests?

**Comment by briangow** [comment]
@WilliamDixon , thanks, this looks good to me!

**Pull request merged**
