### PR TITLE
Adding npy format handler

### PR DESCRIPTION
**Pull request by del42**

### CODE REVIEW

**Comment by briangow** [comment]
Thanks @del42! This is currently failing the fidelity check. The random access read times are also a bit slow:
```
________________________________________________________________
Read performance (median of N trials):
 #seek  #read      KiB      sec     [N]
     6     18   802516   1.0027    [10] read 1 x 214981s, all channels
    30     90  4012580   5.0897     [3] read 5 x 500s, all channels
   300    900 40125800  51.0896     [3] read 50 x 50s, all channels
  3000   9000 401257948 433.7285     [3] read 500 x 5s, all channels
     1      3   104928   0.0780    [85] read 1 x 214981s, one channel
     5     15   521754   0.6123    [14] read 5 x 500s, one channel
    50    150  6482396   7.7419     [3] read 50 x 50s, one channel
   500   1500 67337544  67.0317     [3] read 500 x 5s, one channel
________________________________________________________________
```

**Comment by del42** [comment]
I got the fidelity check passed and performance is better when channels separated by file: 
```
________________________________________________________________
Format: waveform_benchmark.formats.npy.NPY
         (Example format using NPY for storage)
Record: ./data/waveforms/mimic_iv/waves/p100/p10079700/85594648/85594648
         214981 seconds x 6 channels
         255177600 timepoints, 199126720 samples (78.0%)
________________________________________________________________
Channel summary information:
 signal       fs(Hz)     Bit resolution       Channel length(s)   
 II           249.89     0.005(mV)            212497              
 III          249.89     0.005(mV)            5                   
 V            249.89     0.005(mV)            212497              
 aVR          249.89     0.005(mV)            212492              
 Pleth        124.94     0.000244(NU)         212486              
 Resp         62.47      0.000244(Ohm)        212497              
________________________________________________________________
Output size:    802505 KiB (33.01 bits/sample)
Time to output: 0 sec
________________________________________________________________
Fidelity check:

Chunk            Numeric Samples                  NaN Samples
        # Errors  /  Total        % Eq          NaN Values Match
Signal: II
  0              0/  51212896   100.000             Y (7584)    
  1              0/     58944   100.000             Y (1216)    
  2              0/   1818752   100.000             Y (1408)    
Signal: III
  0              0/       960   100.000             Y (320)     
Signal: V
  0              0/  51213248   100.000             Y (7232)    
  1              0/     58944   100.000             Y (1216)    
  2              0/   1818752   100.000             Y (1408)    
Signal: aVR
  0              0/   3982176   100.000             Y (1184)    
  1              0/  47229696   100.000             Y (6144)    
  2              0/     58944   100.000             Y (1216)    
  3              0/   1818752   100.000             Y (1408)    
Signal: Pleth
  0              0/  25610240   100.000              Y (0)      
  1              0/     29440   100.000              Y (0)      
  2              0/    909440   100.000              Y (0)      
Signal: Resp
  0              0/  12805120   100.000              Y (0)      
  1              0/     15040   100.000              Y (0)      
  2              0/    455040   100.000              Y (0)      
________________________________________________________________
Read performance (median of N trials):
 #seek  #read      KiB      sec     [N]
   nan    nan      nan   0.1298    [50] read 1 x 214981s, all channels
   nan    nan      nan   0.4667    [15] read 5 x 500s, all channels
   nan    nan      nan   4.2242     [3] read 50 x 50s, all channels
   nan    nan      nan  40.0215     [3] read 500 x 5s, all channels
   nan    nan      nan   0.0139   [256] read 1 x 214981s, one channel
   nan    nan      nan   0.0504    [71] read 5 x 500s, one channel
   nan    nan      nan   0.5130    [10] read 50 x 50s, one channel
   nan    nan      nan   4.4268     [3] read 500 x 5s, one channel
________________________________________________________________
```
Need help with git sync... @briangow

**Comment by del42** [comment]
@briangow  I tested on 3.9 and it was fine. Could you see if 3.9 works for you. If you prefer 3.11 I will change it, accordingly.

**Comment by briangow** [comment]
@del42 , I'm not sure how this is working for you. From what I can tell `numpy.save` should not accept a tuple - it only accepts an array. You could look into `numpy.savez` instead.

**Comment by briangow** [comment]
@del42 , that is the automated workflow run that @tompollard added. We will ultimately run this on one of our servers for benchmarking.

**Comment by briangow** [comment]
Thanks @del42 , this looks good!

**Pull request merged**
