### PR TITLE
Adding CCDEF Format Class

### PR DESCRIPTION
**Pull request by wa6gz**
This pull request adds a first iteration of CCDEF HDF5, very similar to the WFDB format class. The code uses h5py for file operations. More fidelity checking is needed, but this runs with the benchmarking script.

### CODE REVIEW

**Comment by briangow** [comment]
Thanks @wa6gz ! This is running on our linux server for me but isn't outputting the `#seek`, `#read`, and `KiB` numbers. 

@bemoody , [strace](https://github.com/chorus-ai/chorus_waveform/blob/37f8470e7ce1e3d3493a659c0d7ccaa97325c4c4/waveform_benchmark/ioperf.py#L54) seems to be running without any exception but isn't reporting numbers. Any ideas as to why?

**Comment by tompollard** [comment]
@briangow I've not looked into this in any detail, but as far as I can see `write_waveforms` isn't saving the files.

**Comment by briangow** [comment]
@tompollard despite it not being obvious in the code, I think this is writing the file as expected:

`channel = 'II'`

`write_waveforms`

- set a trap at line 60: `f["Waveforms"][channel].attrs["sample_rate"] = datadict["samples_per_second"]`
- in console enter `f["Waveforms"][channel].attrs["sample_rate"] `
`KeyError: "Unable to synchronously open attribute (can't locate attribute: 'sample_rate')"`
- continue by executing `f["Waveforms"][channel].attrs["sample_rate"] = datadict["samples_per_second"]` and the remaining `attrs` lines. 

`read_waveforms`

- set a trap at line 72, the previous line is: `sample_rate = f["Waveforms"][channel].attrs["sample_rate"]`
- type `sample_rate` in the console:
`249.89`

This shows that even though the `f["Waveforms"].create_dataset(channel,data=sig_samples,compression="gzip", compression_opts=6, shuffle=True)` line is before the code that sets the `attrs`, they are actually written.

**Comment by tompollard** [comment]
@briangow you're right, my bad!

**Comment by bemoody** [comment]
Looks great - thanks, Will!

The "KiB" column probably isn't measured correctly because my cache-busting kludge only works for native Python I/O.  I've just thought of a better way to handle that, so let's ignore that issue for now. :)

As for why "#seek" and "#read" report zeroes... maybe h5py is using mmap?

**Pull request merged**
