### PR TITLE
zarr format updated to bit16int

### PR DESCRIPTION
**Pull request by del42**

### CODE REVIEW

**Comment by briangow** [comment]
@del42 , thanks for this! In my test of this, it seems like you are getting fidelity errors that can't be explained simply from the change to lower precision 16 bit data:

```
Chunk			Numeric Samples				  NaN Samples
	# Errors  /  Total	  % Eq  	  SNR   	NaN Values Match
Signal: II
  0  	  50556794/  51212896	1.281 		 1.8  		    N (7584)    
Subset of unuequal numeric data from input:
[-0.105 -0.1   -0.1   -0.105 -0.1   -0.09  -0.055  0.005  0.1    0.22 ]
Subset of unuequal numeric data from formatted file:
[0 0 0 0 0 0 0 0 0 0]
```

Also, if you make updates and it is convenient, could you separate out the open once, read many code and do a separate PR for that?

**Comment by del42** [comment]
> @del42 , thanks for this! In my test of this, it seems like you are getting fidelity errors that can't be explained simply from the change to lower precision 16 bit data:
> 
> ```
> Chunk			Numeric Samples				  NaN Samples
> 	# Errors  /  Total	  % Eq  	  SNR   	NaN Values Match
> Signal: II
>   0  	  50556794/  51212896	1.281 		 1.8  		    N (7584)    
> Subset of unuequal numeric data from input:
> [-0.105 -0.1   -0.1   -0.105 -0.1   -0.09  -0.055  0.005  0.1    0.22 ]
> Subset of unuequal numeric data from formatted file:
> [0 0 0 0 0 0 0 0 0 0]
> ```
> 
> Also, if you make updates and it is convenient, could you separate out the open once, read many code and do a separate PR for that?

@briangow how are we handling NAN with bit16int, which doesn't represent NAN?

**Comment by briangow** [comment]
> @briangow how are we handling NAN with bit16int, which doesn't represent NAN?

@del42 , I think you could store the NaNs as -32768 and then convert back after reading in the samples. This approach is fairly evident in the CCDEF code, if you want to use that as a template.

**Comment by del42** [comment]
> Also, if you make updates and it is convenient, could you separate out the open once, read many code and do a separate PR for that?

@briangow do I PR them same time or wait for one to merged?

**Comment by briangow** [comment]
@del42 , thanks for the update. The uncompressed version looks good now but the compressed version still has the fidelity check issue. Did you intend to add the gain adjustment to `Zarr_compressed` also?

**Comment by del42** [comment]
> @del42 , thanks for the update. The uncompressed version looks good now but the compressed version still has the fidelity check issue. Did you intend to add the gain adjustment to `Zarr_compressed` also?

Already added!

**Comment by briangow** [comment]
@del42 I don't think your switch to using `fmt` was fully implemented:
`AttributeError: 'Zarr' object has no attribute 'fmt'`

**Comment by briangow** [comment]
This looks good in general, since it'll be easier to test and fix once the "open once, read many" code is implemented I'll merge as-is and the `fmt` issue can be fixed in another PR.

**Pull request merged**
