### PR TITLE
Open once read many

### PR DESCRIPTION
**Pull request by tcpan**
initial partial implementation for the "open once read many times" benchmark.

### CODE REVIEW

**Comment by briangow** [comment]
@tcpan, thanks so much for doing this! I ran this across the waveform suite of files for `DICOM16BitsChunked`, `NPY_Uncompressed`, and `Parquet_Compressed`, see attached [log](https://github.com/user-attachments/files/16664465/benchmark_results_pr94.log). In general, it seems like Numpy and Parquet open and close the files in about the same amount of time but Numpy is much faster at random reads. This also seems to hold up when checking some `Parquet_Uncompressed` results. The Numpy signals are stored as `numpy.mmap` while the Parquet signals are stored as  a PyArrow object (`pyarrow.parquet.core.ParquetFile`). 

I know you were leaving a lot up to the engineer who implements the `open_waveforms` and `read_opened_waveforms` functions. I feel like it might be difficult to make sense of our results if we don't give some more guidance though. I assume that if everyone reads in their signal data as `numpy.mmap` in `open_waveforms` the read times would be very similar across "formats". 

Could you expand upon what you think we should be testing here and offer some guidance that would ensure we are differentiating between formats based on that.

**Comment by briangow** [comment]
@tcpan, I also came across a few minor issues:
- In \_\_main__.py line 124 , there seems to be a typo: `mem_profile = opts.memory_profile` -> `mem_profile = opts.memory_profiling`. This isn't directly related to this PR but I wanted to point it out since I noticed it in the review.
- In benchmark.py 
  - line 59, I see your comment about adding the extra parameters in case they can be used for optimization but `total_length`, `block_length`, and `block_count` aren't being passed along in `reader.open_waveforms`
  - A number of lines are too long according to PEP8 standards
  - It'd be nice to have some comments on lines 443, 481, and 519 to differentiate b/w the tests. Currently this requires reading the code further below to figure out.

**Comment by tcpan** [comment]
with respect to open_waveforms and read_opened_waveforms functions, my suggestion is to use the best practices for the io functions for that format.    If the io functions has the ability to hold open the file for random access later, that would be appropriate.  If the function has to read in the whole signal, then reading it in and hold the signal in memory for random access makes more sense (reopening the files is already part of the original tests.)

I've not yet looked at the results for compression, so no comments yet.

**Comment by bemoody** [comment]
Not really related to the subject matter here, but looking at your first commit: "FIX: random number generator initialization was inside a loop", I don't think this is desirable.

The purpose of `repeat_test` is to run the *same* test multiple times to smooth out noise (though I'm less sure that simply reporting median values is the best way - it'd be better to collect many results and make a box plot.)

More than that, we want to compare the results of the same set of tests across different algorithms.

If you pick random segments of a long heterogeneous waveform record, you should expect to find some segments that are "easy" (few channels, low entropy) and some segments that are "hard" (many channels, high entropy).  So we want to compare how different algorithms perform on the same arbitrarily-chosen list of input segments.

Actually, it looks like I made the same mistake in my very first commit - the code that is now in `_run_read_test_1channel` is doing the wrong thing.  Whoops!

**Comment by tcpan** [comment]
re. random number generator.  I agree with your rationale about having repeatable tests.   The specific change for that commit was more mundane.   In the original version of the code, each iteration of the test would use the same random seed and thus the same sequence of random numbers.  It is likely that the repeated iterations would use the same starting and ending times.   Do we actually get a list of multiple time windows?  or a single time window?

As for the issues Brian raised - I've made the changes and committed.   I changed the "total_length", "block_length" and "block_count" params to a kwargs param.   The benchmark code does not yet pass any parameters or have a good way to pass additional paramters the open_waveforms functions, though.

**Comment by bemoody** [comment]
> Do we actually get a list of multiple time windows? or a single time window?

Yes, if I'm correctly remembering and understanding how this works.

The inner loop `for j in range(block_count)` should arbitrarily pick multiple time windows (e.g., for the 5-second test it should pick 500 different 5-second windows) and should be the same sequence every time.

**Comment by briangow** [comment]
I've opened two new issues to capture a couple of things that have been suggested w/r/t this PR:

[#96: Tidy up benchmarking code](https://github.com/chorus-ai/chorus_waveform/issues/96)
[#97: For the open once, read many test in the benchmarking code - consider combining the open, read(s), and close tests into a single test](https://github.com/chorus-ai/chorus_waveform/issues/97)

**Comment by briangow** [comment]
@tcpan , thanks so much for adding this! It seems to be working well for me. Closes #92

**Pull request merged**
