### PR TITLE
Adds fidelity check

### PR DESCRIPTION
**Pull request by wa6gz**
Checks fidelity of waveform storage using typical command syntax with the "-c" or "--check" flag.
- Iterates chunk by chunk
- Checks for correct NAN placement
- Checks for value correctness using np.isclose()
- Prints summary table
- Prints small subset of incorrectly converted data for chunks with imperfect conversions

Mostly good for identifying that an error exists, could benefit from some better analysis of what doesn't match.

### CODE REVIEW

**Comment by briangow** [comment]
@wa6gz , thanks so much for adding this! Overall, this looks good to me! Perhaps we could clarify things a bit more in the output tables but I'm happy to help with that at some point. In particular, I think making it clear that the `# Errors / Total` and `% Eq` sections are related to the fidelity check and not the NaN check would help. 

Can I ask why you decided to write a separate function, `run_conversion`, instead of integrating the new code into `run_benchmarks`? I would think that in general we would want to run both the tests Benjamin wrote and this fidelity check each time. Since there is a lot of duplicated code between `run_conversion` and `run_benchmarks`, it might be cleaner to integrate your new code into `run_benchmarks` and possibly add a flag for whether to run it (but by default I'd run it). This would alleviate having to keep the duplicated code in sync. I assume @bemoody would be fine with adding to his function. Having said that, I'm happy to merge this now and tackle these potential changes later if you prefer.

**Comment by wa6gz** [comment]
Agreed that the naming/order can be edited to make things more clear. As for the separate files, it started as a way to check my format code without having to run the full benchmarking before I got things running in WSL, and I just left it that way. It could easily be integrated between the conversion and benchmarking code in `run_benchmarks`. I can make these fixes and submit another PR after cleaning it up.

**Comment by wa6gz** [comment]
Latest commit moves the code to benchmark to be run on each iteration, and the output format has been updated to match the existing benchmark code: removed horizontal lines for each signal and column names only printed once at top. This is generally cleaner, if there are errors the output from printing samples will print within the table, but it should still be easy to follow. Table columns were relabeled and rearranged to make it clear which metrics are for numeric samples and which are for NaNs.

**Comment by briangow** [comment]
Thanks @wa6gz , this looks great! 

It's running fine for me in general but when testing the `parquet.Parquet` format I get this error:

```
benchmark.py, line 104, in run_benchmarks
    NANdiff = np.sum(np.isnan(data) != np.isnan(filedata[channel]))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (60160,) (60159,) 
```

perhaps we should have a check to make sure the length of the source and saved data is the same before this line?

**Comment by wa6gz** [comment]
Good call - I added a line checking for an identical shape for each chunk, printing an error and continuing to the next chunk. I can switch this to check length only if we think there are going to be issues matching shapes.

**Pull request merged**
