### PR TITLE
Catch open once read many exception for formats which don't implement required functions

### PR DESCRIPTION
**Pull request by briangow**
This PR catches the `NotImplementedError` exception during the open once read many testing if a format hasn't implemented the required functions. This allows the other tests to run successfully for all formats. 

Apologies for the minor formatting changes, my editor was being boisterous.

### CODE REVIEW

**Comment by tompollard** [comment]
Might be a good idea to just remove the benchmark test...annoying that it keeps failing and probably not worth the effort to fix.

**Comment by tompollard** [comment]
Might be a good idea to add a style check to the tests to try to keep consistent formatting. It looks like black is running over all of your code (presumably on save) which is going to create a bunch of conflicts for anyone happening to be working on the same files.

**Comment by briangow** [comment]
> Might be a good idea to just remove the benchmark test...annoying that it keeps failing and probably not worth the effort to fix.

I agree! We should do in another PR.

**Comment by tompollard** [comment]
> > Might be a good idea to just remove the benchmark test...annoying that it keeps failing and probably not worth the effort to fix.

> I agree! We should do in another PR.

Looking at this more closely, the problem is that the requirements in requirements.txt cannot be resolved. Most likely the problem is a result of WFDB being tied to Numpy v1. See: https://github.com/chorus-ai/chorus_waveform/issues/103

**Comment by tompollard** [comment]
Thanks Brian, looks good to me! Hopefully the formatting changes don't trip anyone up.

**Pull request merged**
